### ISSUE TITLE
Add forwarding proxy example

### ISSUE THREAD

**Issue by nikku** [camunda/zeebe-connection-test#7]
### What shall we do?

Be able to test forwarding proxy related configuration.

**Comment by billbarni** [comment]
Would this allow me to test my self managed zeebe with HTTPs and plaintext=false?

I am having issues creating a simple nginx.conf to use a self-signed cert to do that against my docker-compose.yaml from Camunda 8.2

**Comment by nikku** [comment]
@billbarni You have a reverse proxy ("ingress") that accepts HTTPS traffic and forwards it as HTTPS to Zeebe?

**Comment by billbarni** [comment]
@nikku 
No... I'm trying to build an nginx local configuration with a self-signed certificate to point to zeebe.

Camunda failed me with version 8.2.5 having several auth changes that I could not test beucase the bugs only happened when "plaintext" from zeebe security was set to false and https was on.

Ingress is being used in AWS... but I need some way of testing it locally for the exactly same auth and config as the one we are deploying in AWS.

**Comment by barmac** [comment]
If I understand it correctly, your production architecture looks like this:

![image](https://github.com/camunda/zeebe-connection-test/assets/28307541/1b163ea0-75ad-4873-a06c-b79a09ee5dfa)

And then you want to setup something like this locally:

![image](https://github.com/camunda/zeebe-connection-test/assets/28307541/99f4f240-0aa6-4218-8c3a-1800b995e274)

Correct?

**Comment by billbarni** [comment]
Perfect. And I'm not able to do it using my nginx.conf:

```
worker_processes 1;

events { worker_connections 1024; }

http {
    
    default_type  application/octet-stream;
    keepalive_timeout  65;
    sendfile on;
    large_client_header_buffers 4 32k;

    server {
        listen 443 http2 ssl;
        server_name my-site;

        ssl_certificate /etc/ssl/certs/my-site.crt;
        ssl_certificate_key /etc/ssl/private/my-site.key;
        ssl_verify_client off;

        location / {
            grpc_pass grpc://localhost:26500;
        }
    }

}
```

**Comment by nikku** [comment]
Zeebe is configured like what exactly? Using secured or insecure communication?

#### Insecure Proxy -> Zeebe

```
grpc_pass grpc://localhost:26500;
```

#### Secure Proxy -> Zeebe

```
grpc_pass grpcs://localhost:26500;
```

**Comment by nikku** [comment]
Please checkout [our example](https://github.com/camunda/zeebe-connection-test#test-secure-connection-to-zeebe-via-reverse-proxy), corresponding to https://github.com/camunda/zeebe-connection-test/issues/7#issuecomment-1580594478 and tell us where your setup is different.

You may use [our generate cert utils](https://github.com/camunda/zeebe-connection-test#generate-certificates) to create self-signed certificates in the proper way. Also potentially helpful is the [Desktop Modeler troubleshooting guide](https://docs.camunda.io/docs/components/modeler/desktop-modeler/troubleshooting/#i-cannot-connect-to-zeebe). It links known issues and their resolution.

**Comment by nikku** [comment]
Closing this issue due to lack of user input + unclear goal. If we come up with this use-case ourselves again, then we can act on it.
